plugins: ["react"]
extends: "./node_modules/mofo-style/.eslintrc.yaml"

env:
  es6: true
  node: true
  browser: true

parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: "module"

rules:
  react/jsx-uses-vars: [2]
  react/jsx-uses-react: [2]
  newline-after-var: [0]
  indent: [2, 2, {"SwitchCase": 1}]
  camelcase: [1, properties: "always"]
  curly: [0]
  quotes: [0, "backtick"]
